#!/bin/bash
# harvest-feedback.sh — Extract skill improvement markers from session transcript at SessionEnd
# 
# Marker format: <!-- SKILL_IMPROVEMENT_RECOMMENDATION: {"skill": "...", "description": "..."} -->

set -eo pipefail

# Dependency probe — match the pattern used by detect-quality-review.sh and
# wiki-common.sh:wiki_check_deps. Without this, missing jq fails silently at
# the first jq call and the hook stops harvesting forever with no signal.
if ! command -v jq >/dev/null 2>&1; then
  echo "harvest-feedback: jq not found — feedback harvest disabled (install: brew install jq)" >&2
  exit 0
fi

# Read hook input from stdin
HOOK_INPUT=$(cat)

# Extract transcript path and CWD
TRANSCRIPT=$(echo "$HOOK_INPUT" | jq -r '.transcript_path // ""' 2>/dev/null)
CWD=$(echo "$HOOK_INPUT" | jq -r '.cwd // ""' 2>/dev/null)

[ -z "$TRANSCRIPT" ] && exit 0
[ ! -f "$TRANSCRIPT" ] && exit 0

# Resolve Git Root for the project-scoped backlog location. If we're not
# inside any git repo, skip — writing under $CWD (often $HOME) would
# scatter feedback across unrelated sessions and create surprise dirs.
GIT_ROOT=$(git -C "$CWD" rev-parse --show-toplevel 2>/dev/null || true)
[ -z "$GIT_ROOT" ] && exit 0
BACKLOG_FILE="$GIT_ROOT/tasks/in-progress/prompt-improvements-backlog.md"

# Pattern to look for
PATTERN='<!-- SKILL_IMPROVEMENT_RECOMMENDATION: '

# Ensure backlog file exists with a header if new
if [ ! -f "$BACKLOG_FILE" ]; then
  mkdir -p "$(dirname "$BACKLOG_FILE")"
  printf "# Prompt Improvement Backlog\n\nGenerated by feedback-collector plugin.\n\n" > "$BACKLOG_FILE"
fi

# Extract and process each recommendation
# The transcript might contain JSON escaped characters if it's a JSON transcript,
# but usually it's plain text in the tool output sections.
grep "$PATTERN" "$TRANSCRIPT" | while read -r line; do
  # Extract the JSON part between the marker prefix and the closing -->
  JSON_PART=$(echo "$line" | sed -n "s/.*${PATTERN}\({.*}\) -->.*/\1/p")
  
  if [ -n "$JSON_PART" ]; then
    # Validate with jq
    if echo "$JSON_PART" | jq -e . >/dev/null 2>&1; then
      SKILL=$(echo "$JSON_PART" | jq -r '.skill // "unknown"')
      CAT=$(echo "$JSON_PART" | jq -r '.category // "general"')
      DESC=$(echo "$JSON_PART" | jq -r '.description // ""')
      TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
      
      # Append to backlog in a nice markdown format
      {
        printf "## [%s] %s (%s)\n" "$TIMESTAMP" "$SKILL" "$CAT"
        printf -- "- **Recommendation**: %s\n" "$DESC"
        printf -- "- **Raw**: \`%s\`\n\n" "$JSON_PART"
      } >> "$BACKLOG_FILE"
    fi
  fi
done

exit 0
